FROM node:lts

# Set the working directory
WORKDIR /signeo_app_frontend

# Copy the necessary files to the working directory

COPY .env.dev ./
COPY package.json ./
COPY yarn.lock ./
COPY public ./public
COPY src ./src

# Install the necessary system dependencies for Electron
RUN apt-get update 
#&& apt-get install -y libnss3 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libgtk-3-0 libgbm1 libasound2 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libxrandr2 libxss1 libxinerama1 libfontconfig1 libgl1-mesa-glx xdg-utils 
RUN yarn install

# Expose the necessary port for your application
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl --fail http://localhost:3000 || exit 1

# Start your application
CMD ["yarn", "start"]
